version: '3.9'

#docker run -d --name eventstore -p 2113:2113 -p 1113:1113 eventstore/eventstore
#docker run --rm --name test-redis redis:6.2-alpine redis-server --loglevel warning

services:
  eventstore:
    image: eventstore/eventstore
    environment:
          - EVENTSTORE_CLUSTER_SIZE=1
          - EVENTSTORE_RUN_PROJECTIONS=All
          - EVENTSTORE_START_STANDARD_PROJECTIONS=true
          - EVENTSTORE_EXT_TCP_PORT=1113
          - EVENTSTORE_HTTP_PORT=2113
          - EVENTSTORE_INSECURE=true
          - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
          - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true    
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - es-demo:/var/lib/eventstore

  redis:
    image: redis:7.0.2-alpine
    command: redis-server --save 20 1 --loglevel warning 
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - es-demo-redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes:
  es-demo:
  es-demo-redis:
